# Generated by Django 4.2.4 on 2024-03-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="profile.jpg",
                        null=True,
                        upload_to="profile_pic/CustomerProfilePic/",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=40, null=True)),
                ("mobile", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("feedback", models.CharField(max_length=500)),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_image/"
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("mobile", models.CharField(max_length=20, null=True)),
                ("order_date", models.DateField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Order Confirmed", "Order Confirmed"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Delivered", "Delivered"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecom.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecom.product",
                    ),
                ),
            ],
        ),
    ]
