# Generated by Django 4.2.4 on 2023-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipapp', '0002_rename_membershipplan_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(help_text='Enter each feature on a new line'),
        ),
    ]
