# Generated by Django 4.2.4 on 2023-09-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipapp', '0003_alter_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
