# Generated by Django 4.2.4 on 2023-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipapp', '0007_payment_mem_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_mem',
            name='razorpay_order_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
