# Generated by Django 4.2.4 on 2023-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipapp', '0008_payment_mem_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_mem',
            name='status',
            field=models.CharField(choices=[('0', 'Deactivated'), ('1', 'Activated')], default='1', max_length=1),
        ),
    ]
