# Generated by Django 4.2.4 on 2024-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fixture", "0010_alter_fixture_id_alter_match_id_alter_player_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_round",
            field=models.IntegerField(default=0),
        ),
    ]
