# Generated by Django 4.2.4 on 2024-03-02 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
