# Generated by Django 4.2.4 on 2023-08-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
