# Generated by Django 4.2.4 on 2023-09-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='fname',
        ),
    ]
