# Generated by Django 4.2.4 on 2023-09-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_rename_full_name_userprofile_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_of_birth',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
