# Generated by Django 4.2.4 on 2023-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_rename_date_of_birth_userprofile_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_refere',
            field=models.BooleanField(default=False),
        ),
    ]
