# Generated by Django 4.2.4 on 2024-01-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_customuser_is_customer_customuser_is_refere'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
