# Generated by Django 4.2.4 on 2024-02-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.EmailField(max_length=254)),
                (
                    "client_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("booking_date", models.DateField()),
                ("booking_start_time", models.TimeField()),
                ("booking_end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="EventUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default,1=Hidden"),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="img/")),
                ("close_event_date", models.DateField(blank=True, null=True)),
                ("max_registrations", models.PositiveIntegerField(default=100)),
                (
                    "current_registrations",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "accept_status",
                    models.BooleanField(default=False, help_text="Accept Status"),
                ),
                (
                    "reject_status",
                    models.BooleanField(default=False, help_text="Reject Status"),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile_Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("adhar", "Adhar card"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                        ],
                        default="adhar",
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(default="img1.jpg", upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
                ("game_level", models.CharField(max_length=20)),
                ("dob", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainingVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("trainer", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="training_videos/")),
            ],
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="winners/")),
                ("name", models.CharField(max_length=100)),
                ("prize", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_type", models.CharField(max_length=10)),
                ("name1", models.CharField(max_length=100)),
                ("dob1", models.DateField()),
                ("name2", models.CharField(blank=True, max_length=100, null=True)),
                ("dob2", models.DateField(blank=True, null=True)),
                ("contact_number", models.CharField(max_length=15)),
                ("declaration_accepted", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shuttleapp.eventuser",
                    ),
                ),
            ],
        ),
    ]
