# Generated by Django 4.2.4 on 2023-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
    ]
