# Generated by Django 4.2.4 on 2024-03-11 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuttleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('feedback', models.TextField(null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('good', models.BooleanField(default=True, verbose_name='good')),
                ('bad', models.BooleanField(default=True, verbose_name='bad')),
                ('neutral', models.BooleanField(default=True, verbose_name='neutral')),
                ('rating', models.CharField(max_length=100, null=True)),
                ('can_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
