# Generated by Django 4.2.4 on 2023-08-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0003_membershipplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
