# Generated by Django 4.2.4 on 2023-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0008_delete_timeslot_rename_booking_date_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('highestqualification', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('aboutyourself', models.CharField(blank=True, max_length=600, null=True)),
                ('fulladdress', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
