# Generated by Django 4.2.4 on 2023-09-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0011_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
