# Generated by Django 4.2.4 on 2023-09-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0012_remove_registration_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileverification',
            old_name='user',
            new_name='userpro',
        ),
    ]
