# Generated by Django 4.2.4 on 2023-09-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0013_rename_user_profileverification_userpro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileverification',
            old_name='buisness_license',
            new_name='file_upload',
        ),
    ]
