# Generated by Django 4.2.4 on 2023-09-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0014_rename_buisness_license_profileverification_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileverification',
            name='file_upload',
            field=models.FileField(upload_to='images/'),
        ),
    ]
