# Generated by Django 4.2.4 on 2023-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0015_alter_profileverification_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileverification',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='profileverification',
            name='proof_type',
        ),
        migrations.RemoveField(
            model_name='profileverification',
            name='userpro',
        ),
        migrations.AddField(
            model_name='profileverification',
            name='category',
            field=models.CharField(choices=[('adhar', 'Adhar card'), ('passport', 'Passport'), ('driving_license', 'Driving License')], default='adhar', max_length=50),
        ),
        migrations.AddField(
            model_name='profileverification',
            name='image',
            field=models.ImageField(default='img1.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profileverification',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
