# Generated by Django 4.2.4 on 2023-09-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0016_remove_profileverification_file_upload_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileVerification',
            new_name='Profile_Verification',
        ),
    ]
