# Generated by Django 4.2.4 on 2023-09-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0018_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
