# Generated by Django 4.2.4 on 2023-09-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0019_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('booking_date', models.DateField()),
                ('booking_start_time', models.TimeField()),
                ('booking_end_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
