# Generated by Django 4.2.4 on 2023-09-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0021_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='close_event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
