# Generated by Django 4.2.4 on 2023-09-27 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuttleapp', '0024_eventuser_accept_status_eventuser_reject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='org_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
