# Generated by Django 4.2.4 on 2023-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleapp', '0025_eventuser_org_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='current_registrations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
